apiVersion: 1

datasources:
  - name: k6influxdb
    type: influxdb
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: k6io
      defaultBucket: k6io
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB_TOKEN

  - name: claude-influxdb
    uid: claude-influxdb
    type: influxdb
    url: http://influxdb:8086
    isDefault: false
    database: claude
    jsonData:
      httpMode: GET
      tlsSkipVerify: true

  - name: metrics-influxdb
    uid: metrics-influxdb
    type: influxdb
    url: http://metrics-influxdb:8086
    isDefault: false
    user: grafana
    jsonData:
      dbName: metrics
      httpMode: GET
    secureJsonData:
      password: $METRICS_INFLUXDB_READ_PASSWORD
